[server]
listen_http = 0.0.0.0:8990

[theme]
path = /theme
url_base = /theme

[source.rs1]
name = RS1 Mock
[source.rs1.birdwatcher]
api = http://127.0.0.1:29999/
type = multi_table
peer_table_prefix = T
pipe_protocol_prefix = M
