CREATE TABLE sessions(token TEXT PRIMARY KEY,csrf TEXT NOT NULL,expires REAL NOT NULL, user_id INTEGER REFERENCES users(id));
CREATE TABLE locations(code TEXT PRIMARY KEY,name TEXT NOT NULL,source TEXT NOT NULL,general TEXT NOT NULL,clients TEXT NOT NULL,revision INTEGER NOT NULL DEFAULT 1);
CREATE TABLE machines(id TEXT PRIMARY KEY,location TEXT NOT NULL,name TEXT NOT NULL,host TEXT NOT NULL,router_id TEXT NOT NULL,ssh_user TEXT NOT NULL DEFAULT 'root',ssh_port INTEGER NOT NULL DEFAULT 22,status TEXT NOT NULL DEFAULT 'unverified',bird_version TEXT,checked_at REAL,revision INTEGER NOT NULL DEFAULT 1, ssh_key TEXT);
CREATE TABLE jobs(id TEXT PRIMARY KEY,machine TEXT NOT NULL,location TEXT NOT NULL,revision INTEGER NOT NULL,machine_revision INTEGER NOT NULL,status TEXT NOT NULL,created REAL NOT NULL,log TEXT NOT NULL DEFAULT '',config TEXT,sha256 TEXT,validated_sha TEXT,validated_version TEXT);
CREATE TABLE events(id INTEGER PRIMARY KEY,at REAL NOT NULL,kind TEXT NOT NULL,detail TEXT NOT NULL,actor TEXT NOT NULL);
CREATE INDEX idx_jobs_machine_status ON jobs(machine,status);
CREATE INDEX idx_jobs_created ON jobs(created);
CREATE TABLE sqlite_stat1(tbl,idx,stat);
CREATE TABLE member_conversations(chat_id INTEGER PRIMARY KEY,step INTEGER NOT NULL,data TEXT NOT NULL,updated REAL NOT NULL);
CREATE TABLE member_requests(id TEXT PRIMARY KEY,chat_id INTEGER NOT NULL,user_id INTEGER NOT NULL,username TEXT NOT NULL,data TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'pending',created REAL NOT NULL,reviewed REAL,reviewer TEXT,reason TEXT NOT NULL DEFAULT '',revision INTEGER, origin TEXT NOT NULL DEFAULT 'telegram', application_id TEXT);
CREATE UNIQUE INDEX member_pending ON member_requests(chat_id) WHERE status='pending';
CREATE TABLE telegram_meta(key TEXT PRIMARY KEY,value TEXT NOT NULL);
CREATE TABLE telegram_outbox(id INTEGER PRIMARY KEY,chat_id INTEGER NOT NULL,text TEXT NOT NULL,created REAL NOT NULL,sent REAL,attempts INTEGER NOT NULL DEFAULT 0,next_try REAL NOT NULL DEFAULT 0,error TEXT);
CREATE TABLE IF NOT EXISTS "users"(id INTEGER PRIMARY KEY,name TEXT NOT NULL UNIQUE,salt TEXT NOT NULL,password TEXT NOT NULL,role TEXT NOT NULL DEFAULT 'super-admin' CHECK(role='super-admin'));
CREATE TABLE member_applications(id TEXT PRIMARY KEY,created REAL NOT NULL,asn INTEGER NOT NULL,organization TEXT NOT NULL,email TEXT NOT NULL,location TEXT NOT NULL,peering_ipv4 TEXT,peering_ipv6 TEXT,ipv4_prefixes TEXT,ipv6_prefixes TEXT,bandwidth TEXT NOT NULL,domain TEXT NOT NULL,pairing_code TEXT NOT NULL,pairing_verified INTEGER NOT NULL DEFAULT 0,pairing_verified_at REAL, telegram_code TEXT);
CREATE TABLE ports(id INTEGER PRIMARY KEY,switch_id INTEGER NOT NULL REFERENCES switches(id) ON DELETE CASCADE,member_asn INTEGER NOT NULL,port_number TEXT NOT NULL,type TEXT NOT NULL,status TEXT NOT NULL,bandwidth TEXT NOT NULL, mac_address TEXT,UNIQUE(switch_id,port_number));
CREATE TABLE nodes(id INTEGER PRIMARY KEY,location TEXT NOT NULL REFERENCES locations(code),name TEXT NOT NULL,created REAL NOT NULL DEFAULT (strftime('%s','now')));
CREATE TABLE IF NOT EXISTS "switches"(id INTEGER PRIMARY KEY,node_id INTEGER REFERENCES nodes(id) ON DELETE CASCADE,name TEXT NOT NULL,ip TEXT NOT NULL,community TEXT NOT NULL,vendor TEXT,model TEXT,sys_name TEXT,sys_descr TEXT,created REAL NOT NULL DEFAULT (strftime('%s','now')));
CREATE TABLE member_telegram_chats(asn INTEGER, chat_id INTEGER, PRIMARY KEY(asn, chat_id));
CREATE TABLE iixji_members(id INTEGER PRIMARY KEY,asn INTEGER,name TEXT,type TEXT,status TEXT,contact TEXT,notes TEXT,created REAL);
CREATE UNIQUE INDEX member_request_application ON member_requests(application_id) WHERE application_id IS NOT NULL;
CREATE TABLE stats_public_ports(port_id INTEGER PRIMARY KEY REFERENCES ports(id) ON DELETE CASCADE,enabled INTEGER NOT NULL DEFAULT 0,created REAL NOT NULL DEFAULT (strftime('%s','now')));
CREATE TABLE stats_public_groups(id INTEGER PRIMARY KEY,name TEXT NOT NULL,mode TEXT NOT NULL DEFAULT 'selected',port_ids TEXT NOT NULL DEFAULT '[]',enabled INTEGER NOT NULL DEFAULT 1,created REAL NOT NULL DEFAULT (strftime('%s','now')));
