[server]
listen_http = 0.0.0.0:8990

[theme]
path = /theme
url_base = /theme

[source.sub-rs2]
name = RS2 Surabaya

[source.sub-rs2.birdwatcher]
api = http://103.19.76.2:29999/
type = multi_table
peer_table_prefix = T
pipe_protocol_prefix = M

[source.sub-rs3]
name = RS3 Surabaya

[source.sub-rs3.birdwatcher]
api = http://103.19.76.3:29999/
type = multi_table
peer_table_prefix = T
pipe_protocol_prefix = M

[source.ag-rs1]
name = RS AG Tulungagung

[source.ag-rs1.birdwatcher]
api = http://103.19.76.14:29999/
type = multi_table
peer_table_prefix = T
pipe_protocol_prefix = M

[source.b56426ea7836da0d]
name = RS5-LAMONGAN

[source.b56426ea7836da0d.birdwatcher]
api = http://103.19.76.15:29999/
type = multi_table
peer_table_prefix = T
pipe_protocol_prefix = M
