server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;
    location / { try_files $uri $uri/ /index.html; }
    location /api/public/ {
        proxy_pass http://arouterserver-dashboard:8989/api/public/;
        proxy_set_header Host $host;
    }
}
